### ISSUE TITLE
Not able to commit JS and HTML file under capitalone/Hygieia

### ISSUE THREAD

**Issue by amrita1-2** [capitalone/Hygieia#1039]
Not able to commit JS and HTML file under capitalone/Hygieia. Please let us know as we have to contribute an enhancement to Hygieia Dashboard.

**Comment by mrpudn** [comment]
We need a little more info - what do you mean you aren't able to commit JS and HTML files?

Do you have some command-line output that we can look at in order to assist you?

If this is regarding the Contributing Agreements, please refer to the below:
  - [Capital One Services, LLC Individual Contributor License Agreement v2.0](https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform)
  - [Capital One Services, LLC Software Grant and Corporate Contributor License Agreement v1.0](https://docs.google.com/forms/d/e/1FAIpQLSeAbobIPLCVZD_ccgtMWBDAcN68oqbAJBQyDTSAQ1AkYuCp_g/viewform)

**Comment by satishc1** [comment]
Closed. Re-open with additional details if still an issue.
