### ISSUE TITLE
Not able to see jira count i.e wip and open

### ISSUE THREAD

**Issue by abhishekvats007** [capitalone/Hygieia#1066]
jira collector i am able to see the issues in progress though the count of open and WIP is 0. I am not getting what this count refers to ? I understand that open signifies the number of issues that are open and WIP signifies number of issues that are marked in progress.

![l_ca9 tmp](https://cloud.githubusercontent.com/assets/17519769/21640474/b9b6aeb2-d29b-11e6-92bb-36bb7eaa3e13.PNG)

**Comment by MarkRx** [comment]
It is the story points or hours estimate depending on what you select. If you don't have values for those you either didn't configure the fields correctly or your jira instance does not have them set up.

**Comment by abhishekvats007** [comment]
I have selected Kanban. Is it possible to see issues in open and issues in WIP state using this widget?

**Comment by MarkRx** [comment]
If you want the number of issues instead of estimates then you will want PR #1054. It has not been merged yet.

**Comment by satishc1** [comment]
@abhishekvats007 The feature widget now has an option to display metrics based on the number of tickets instead of estimates. This is for setups that do not use estimates.
Functionality merged in https://github.com/capitalone/Hygieia/pull/1054 Use latest codebase. You’ll also need to follow cleanup instructions provided in https://github.com/capitalone/Hygieia/pull/1137
