### ISSUE TITLE
The stages data of one team dashboard pipeline can't be reused by another team level dashboard

### ISSUE THREAD

**Issue by wdquan1985** [capitalone/Hygieia#1183]
Create one team level dashboard, named teamDash1, then import build info and commit info of one project  to this dashboard, add this team level dashboard to a product level dashboard, the stages data of teamDash1 pipeline can be shown in the product level dashboard.
![teamdash1](https://cloud.githubusercontent.com/assets/15209842/23055955/d0e633be-f523-11e6-9997-d3eac596ee92.png)

But if I delete teamDash1, create a new teamDash2, and import the same data to it, the stages data of teamDash2 pipeline can't be shown in the product level dashboard. Why can't reuse the the stages data of teamDash1 pipeline?  How to reuse it?

If we can't reuse it because of some design reason, the teamDash1 pipeline is still in the database, it has not been deleted when teamDash1 deleted. And mybe the pipeline data will never be used, such dirty data should be deleted. 
![database](https://cloud.githubusercontent.com/assets/15209842/23055991/033754ce-f524-11e6-832a-493ebdc5d753.png)

At last, I think to reuse it is the best way.

**Comment by wdquan1985** [comment]
I have read the code, build stage data will be created only when the build saved to database, and this build stage data only belongs to one team level dashboard, the same to other stages. So if I create another team level dashboard, and import the same build data, build stage data will not be created for this new team level dashboard, because the build data will not be saved to database again.

**Comment by MarkRx** [comment]
It's a shortcoming of the current design. The pipeline is not filled with data until after it is created. #804

There is a hidden feature you can try by adding this to api.properties:

> feature.dynamicPipeline=enabled

It may need a few updates to work with the latest code. I have not had the time to update it yet. You can turn on debugging to see what it is doing. Basically the idea is to build the pipeline data on demand instead of building it when collectors run.

Here are my notes from a buried story on my backlog of things to do:
- Improve logging:
  - no commits found vs none in job
  - show full commit graph?
- Improve branch equality - origin/master vs master
- improve environment logging when a commit is not found (specify which environment)
- All commits vs bounded commits
- case sensitivity of component names vs artifact names
- Bug: the last commit in a graph is currently bound but we are adding their parent revision numbers into the commit graph. This results in an additional commit that we don't have knowledge of
- where does average of 35D come from for helloworld?

**Comment by wdquan1985** [comment]
I have debugged the dynamicPipeline feature, now I know how to produce pipeline stages data and how to show them.
(1). How to produce build stage data.
This feature will get only SCM info of the last build for one commit, then store it to the build stage. Why it don't collect all the build SCM info for one commit ?
(2). How to show commit stage data.
When get commit stage data from database, this feature will check build stage data first, if build stage data's scmRevisionNumber is same to commit stage data, commit stage data will be ignored and can't be shown. In my CI process, one commit automaticlly trigger one build, there will not be commit which has not been built, so the commit stage will always be blank, it can't show the average time of all the commits. 
I think keeping the commit data which have same scmRevisionNumber with build stage data is a better choice.
![commitstage](https://cloud.githubusercontent.com/assets/15209842/23351061/bd62ba64-fcf9-11e6-92d8-2cb186147acd.png)

**Comment by MarkRx** [comment]
You can't fill the SCM data from the build because not all of the necessary fields are available from the build collectors. That is why they are looked up.

**Comment by wdquan1985** [comment]
About the pipeline commit stage data.
 There are commit stage data in the database.
![pipedata](https://cloud.githubusercontent.com/assets/15209842/23397568/0b9d53f8-fdd4-11e6-81c2-99a2abb67a5d.png)
But the commit stage data can't be shown in the dashboard.
![commitnotshow](https://cloud.githubusercontent.com/assets/15209842/23397609/3aa678aa-fdd4-11e6-8a85-65ad8834ebea.png)
I have checked the code, and found the root cause, if build stage data's scmRevisionNumber is same to commit stage data, commit stage data can't be shown. so the commit stage will always be blank, it can't show the average time of all the commits. If I just want to the average time of commits, How to do it?

**Comment by MarkRx** [comment]
Yes I think that is the way the product view works right now (note it works they way regardless of the state of that feature switch). I agree that metrics should still show up even if no commits are in that exact stage.
