### ISSUE TITLE
Simple Custom URL Widget

### ISSUE THREAD

**Issue by hughbrien** [capitalone/Hygieia#132]
How Can I create a Custom Widget that will render a URL? 

Do I need to start with cloning and existing collector?

**Comment by amitmawkin** [comment]
could you elaborate more on your usecase, are you asking how to write a widget that will just render a URL link, URL content ?

**Comment by hughbrien** [comment]
Actually both, but lets start with URL Content, so I was thinking "IFRAME", but that could be dated. 

This would be an example of a URL : https://comcast27.saas.appdynamics.com/controller/dashboards.jsp#/location=DASHBOARD_VIEWER&token=c786e31c-d6bc-4b9e-9988-9d0ac2e9122a&timeRange=last_1_day.BEFORE_NOW.-1.-1.1440

**Comment by hughbrien** [comment]
Any thoughts on this.

**Comment by amitmawkin** [comment]
Widget actually talks to api which in turn pulls data from mongodb, now it should be non trivial to pull exactly the data that's shown in pie chart directly and use chartist which we use to display it in pie chart instead of an IFRAME, as with IFRAME as you said first its dated and second you loose css customizations and look and feel of the dashboard.

**Comment by hughbrien** [comment]
So just create a new "Widget" in Java and go from there?

**Comment by tabladrum** [comment]
Closing this as @hughbrien and we are working towards a better push solution.
