### ISSUE TITLE
Hygieia jenkins plugins build issues

### ISSUE THREAD

**Issue by maheshgohil1989** [capitalone/Hygieia#1350]
I try to build Hygieia jenkins plugins by executing comand - mvn clean package and got below errors

[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.106 is missing
, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:hygieia-publ
isher:hpi:2.0.5-SNAPSHOT
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:
2.0.5-SNAPSHOT (D:\Installation\hygieia\code\Hygieia\hygieia-jenkins-plugin\pom.
xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugin
s:plugin, please verify your project structure @ line 15, column 13
[WARNING] 'build.plugins.plugin.version' for org.jacoco:jacoco-maven-plugin is m
issing. @ line 190, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t
he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin
g such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Hygieia Publisher Plugin 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/1
.609.2/jenkins-war-1.609.2.war
Downloading: http://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/1
.609.2/jenkins-war-1.609.2-war-for-test.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:50 min
[INFO] Finished at: 2017-04-24T15:47:57+05:30
[INFO] Final Memory: 28M/597M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve d
ependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPS
HOT: The following artifacts could not be resolved: org.jenkins-ci.main:jenkins-
war:war:1.609.2, org.jenkins-ci.main:jenkins-war:jar:war-for-test:1.609.2: Could
 not transfer artifact org.jenkins-ci.main:jenkins-war:war:1.609.2 from/to repo.
jenkins-ci.org (http://repo.jenkins-ci.org/public/): GET request of: org/jenkins
-ci/main/jenkins-war/1.609.2/jenkins-war-1.609.2.war from repo.jenkins-ci.org fa
iled: Premature end of Content-Length delimited message body (expected: 68976099
; received: 13944387 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

**Comment by maheshgohil1989** [comment]
Today i build again and able to build successfully. You can close this ticket.

**Comment by Naumansh2** [comment]
HI Mahesh,

I have been facing same problem and error. I would really appreciate if you could help me getting it fixed

C:\Hygieia\Hygieia-master\hygieia-jenkins-plugin>mvn clean package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.0.5-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:2.0.5-SNAPSHOT (C:\Hygieia\Hygieia-master\hygieia-jenkins-plugin\pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 14, column 13
[WARNING] 'build.plugins.plugin.version' for org.jacoco:jacoco-maven-plugin is missing. @ line 203, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Hygieia Publisher Plugin 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.600 s
[INFO] Finished at: 2017-11-27T02:27:54+05:00
[INFO] Final Memory: 19M/186M
[INFO] ------------------------------------------------------------------------
[ERROR] 26921
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
