### ISSUE TITLE
Rundeck Configuration with Hygieia 

### ISSUE THREAD

**Issue by ritusingh16** [capitalone/Hygieia#1353]
Configured rundeck webhook with hygieia sucessfully

But I am not able to see those rundeck job in pipeline view or in Deploy widget.

**Comment by nireeshT** [comment]
@ritusingh16  - check the webhook url configured in rundeck job
http://<apihost>:<apiport>/api/deploy/rundeck?artifactNameParam=deploymentUnit

**Comment by ritusingh16** [comment]
@nireeshT 
Thanks for reply

Yes I have configured that 
Please find the attached document which contain screenshot 

[Configuration in rundeck as follows.docx](https://github.com/capitalone/Hygieia/files/963426/Configuration.in.rundeck.as.follows.docx)

**Comment by nireeshT** [comment]
@ritusingh16  - 
1) You seem to be working on outdated code, because your delivery pipeline widget shows the old UI, unless you configured to use dynamicpipeline enabled in dashboard.properties.
2) if deploy widget config modal is showing "Loading" in dropdown, share screenshot of browser console, it should show an error at the line it broke in js.

**Comment by ritusingh16** [comment]
@nireeshT 
Thanks for help
