### ISSUE TITLE
Proposal: Securing APIs

### ISSUE THREAD

**Issue by satishc1** [capitalone/Hygieia#1386]
@tabladrum @rob-miller-777 
In terms of securing APIs with some sort of token do you think this is a valid approach?

When an external system wants to make a call to a secure API in hygieia, the hygieia admin could generate a JWT token for them. The input for creating the token would be some identifier (key) and an expiration date. We wouldn't store the JWT token in hygieia, but we would store the identifier and the expiration date to have a record that a JWT token was issued to the calling system.

The calling system would pass in the token in the header of their call. We would decode the token to see its component parts that would give us the identifier.

A JWT token isn't really meant to be revoked, but at some point if we do wish to revoke the token we could use the "identifier" to somehow block it.

**Comment by rob-miller-777** [comment]
I had considered using a JWT token, but I don't think that would be appropriate in this scenario.  JWT tokens are meant to have short life cycles, since they are valid until they expire, so I was thinking that we might want to take a different approach.  My thought would be to store API keys in the database, and check them on each request.  If we start to check JWT tokens to see if they have been revoked on each request, we lose the benefit of them being stateless. We could add something to the admin page to handle generating new api keys, and managing them there.  I created #1372 , nested routes, with the idea that we could really build out the admin functionality of the app.

**Comment by satishc1** [comment]
@rob-miller-777 I agree ..its better to store API keys. I can merge https://github.com/capitalone/Hygieia/pull/1372 . Do you have something already in progress for the API keys? I have some screens now but they are JWT token creation based.

**Comment by rob-miller-777** [comment]
I don't have anything going for the API key stuff yet, all you.

**Comment by satishc1** [comment]
@rob-miller-777 No worries. I'll get that PR merged and re-work the token screens.

**Comment by rob-miller-777** [comment]
Sounds good, let me know when you have a pull request out there for the token stuff and I'll take a look.

**Comment by satishc1** [comment]
Closed. We will use api keys instead of a JWT token to secure the api.
