### ISSUE TITLE
make it a little easier to run Hygieia for new users via maven

### ISSUE THREAD

**Issue by jstrachan** [capitalone/Hygieia#14]
I banged my head a bit getting all the parts built and running. 

To make my life easier at least - and hopefully others giving the project a try - I've hacked up 

* a little root maven pom.xml so you can build the common java stuff from the root directory
* made it easy to run things via the maven command line to avoid folks having to do much spring boot configuration on startup etc
* added a little bit more logging on startup so you can see what the effective configuration is for mongo / jenkins / github etc so you can be sure that the spring boot configuration magic is properly working ;)
* polished the README.md's a little here or there

A PR on its way shortly...

**Comment by bodiam** [comment]
What's the status on this one? I was actually going to propose to get rid of everything from Maven, since it seems a bit confusing to me to have 2 build systems (Gradle is also in now). I don't have strong feelings for and against either, but I do have strong feelings for having one option. What are your ideas on that?

**Comment by amitmawkin** [comment]
closing the issue as this is achieved. the UI and api are easy to run now
