### ISSUE TITLE
User already exists issue

### ISSUE THREAD

**Issue by petro-osypenko-lebara** [capitalone/Hygieia#1443]
I used this quite straight guide to build Hyigiea on Windows 10
http://www.smlcodes.com/tutorials/hygieia-dashboard-tutorial/

UI and API layers are up. I can see API connectivity as a green check mark.
However when trying to sign up with any new account it says "User already exists"

Any suggestions?

**Comment by dsanchezseco** [comment]
Same here using docker images

**Comment by nireeshT** [comment]
@petro-osypenko-lebara @dsanchezseco  - Looking into it. Keep you posted.

**Comment by dsanchezseco** [comment]
I solved on the docker part. The problem is with a config variable missing on the Hygieia/api/docker/properties-builder.sh (jaspyt, which is required no matter you use ENC() on dockerfile or not) and two env vars that are missing on the dockerfile and don't have default values.

dockerfile
```
ENV AUTH_EXPIRATION_TIME=36000
ENV AUTH_SECRET=secret
```
properties-builder.sh
```
jasypt.encryptor.password=hygieiasecret

#Authentication Settings
# JWT expiration time in milliseconds
auth.expirationTime=${AUTH_EXPIRATION_TIME:-}
# Secret Key used to validate the JWT tokens
auth.secret=${AUTH_SECRET:-}
```

**Comment by willuk2010** [comment]
Had the same issue last month, ( https://github.com/capitalone/Hygieia/issues/1401 ) and fixed it as you did.

**Comment by nireeshT** [comment]
@petro-osypenko-lebara  - refer #1401  . Reopen if issue still exists.
