### ISSUE TITLE
Pull latest docker images from docker public repository

### ISSUE THREAD

**Issue by saxenadeepakkumar** [capitalone/Hygieia#1873]
Hi Team,

I want to setup Hygieia on my System using docker-compose. So, I want to pull latest images from docker public repository. But I found that latest/versioned images  are not available in docker public [repo](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=capitalone&starCount=0) (for example, [hygieia-ui](https://hub.docker.com/r/capitalone/hygieia-ui/tags/) image is pushed before 2 years). 
**Do you push latest images to docker public repo or any  other repo, when you released? So that, I can pull latest/versioned images from there.**
Otherwise, I have to setup Hygieia's code on my system and create docker images. In that case, I have to repeat this step whenever new released will be available.

Thanks,

**Comment by matthewbeasley** [comment]
Hey saxenadeepakkumar! Integrating a push of our latest images to Docker Hub into our release process is definitely something on our radar. As you correctly pointed out you currently need to pull the latest code from the repo in order to get the latest and greatest version of Hygieia. This will change sometime in the near future. Thank you for your feedback and do let us know if you have other issues with the docker set up.
