### ISSUE TITLE
where the data come from in Security Scan & Open Source Scan & Test Result of Code Analysis

### ISSUE THREAD

**Issue by ganshanshan** [capitalone/Hygieia#1954]
Dear ALL

We plan to use the Hygieia, but I can not get any data from Security Scan & Open Source Scan & Test Result of Code Analysis.Could anyone tell me how I can feed the Security Scan & Open Source Scan & Test Result? Thanks very much.

![image](https://user-images.githubusercontent.com/19347709/35255035-eb9e0c30-0027-11e8-8e7e-3bf83476ae68.png)

**Comment by ganshanshan** [comment]
Hi @tabladrum ,could you help me?

**Comment by tabladrum** [comment]
Sure. Do you use any standard tool for your security scan and open source scan?
For test results - right now it only works with Cucumber tests and that is because the Jenkins plugin can publish cucumber test results into Hygieia. However, technically, any test results can be published if you call the API or write a new collector for your tool.

**Comment by ganshanshan** [comment]
Got it,thanks @tabladrum .
