### ISSUE TITLE
stash-collector only stores most recent commit (Latest commit)

### ISSUE THREAD

**Issue by neetusanjay** [capitalone/Hygieia#199]
I am trying to use stash collector for code repo wedget, But it always shows most latest commit only. commit collection also has only single entry. 

As you can see it pull multiple commits...but only saves one. 

Any help will be greatly appreciated. 

![capture3](https://cloud.githubusercontent.com/assets/13186518/11707793/968a4286-9ed6-11e5-8996-b78b30437161.JPG)

![capture2](https://cloud.githubusercontent.com/assets/13186518/11707778/6a687ef2-9ed6-11e5-9f3a-820468a0b528.JPG)

![capture](https://cloud.githubusercontent.com/assets/13186518/11707696/bb66d624-9ed5-11e5-841b-4385efc6238f.JPG)

**Comment by neetusanjay** [comment]
#Collector schedule (required)
git.cron=0 0/1 * * * *

#mandatory
git.host=https://stash.com/   --my stash url

#mandatory
git.api=/rest/api/1.0/

#Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=30

git.firstRunHistoryDays=30



git.jpa.show-sql: true

**Comment by neetusanjay** [comment]
Above issue was resolved as we still used stash instead of bitbucket. The change to resolve this issue was adding compoenent annotation on DefaultStashClient class (removing it from DefaultBitbucketClient).

**Comment by vtaneeru** [comment]
We are using bitbucket and getting commits. But they are displayed under old dates even though we have some commits today.

**Comment by kv113813** [comment]
Hi All,

Stash only shows one commit on code repo:
I using below properties..

STASH_HOST=gitscm.com/
STASH_API=git.api=/rest/api/1.0/
STASH_CRON:-0 * * * * *
git.commitThresholdDays=30
git.firstRunHistoryDays=30
git.jpa.show-sql=true
code repo type=stash
code repo url= https://gitscm.com/projects/projectname/repos/demo.git
branch=master

**Comment by aryasunny** [comment]
@vtaneeru what are the properties you are using in your application.properties file.

And your bitbucket widget works even though you chose repo type as stash while setting up the widget ??

Do you know what exactly is the api URL that is being used to fetch the stats from bitbucket server ??

I have a repository on bitbucket but when I try to configure my bitbucket widget, I get an error in my stash-scm-collector, i.e 404 not found on the api URL that is getting formed

my application.properties file

#mandatory
git.host=https://bitbucket.org
#mandatory
git.api=/rest/api/1.0/

Note: I have a repository at bitbucket which I am giving to the widget. Final api URL that forms is -->
https://bitbucket.org/rest/api/1.0/aryasunny/renewal/commits?sha=feature/develop&since=2016-0
4-12T21:08Z
