### ISSUE TITLE
Installation Confusion 

### ISSUE THREAD

**Issue by Avfdo1994** [capitalone/Hygieia#2103]
Hi, 
Should the properties for the collectors be placed in separate files (Eg.  D:\Hygieia\collectors\scm\github\github.properties) or should they be placed within the dashboard.properties file found within (D:\Hygieia\api\dashboard.properties).?

Should i configure the application.properties file found within D:\Hygieia-Test\Hygieia\api\src\main\resources?

I've installed my Dashboard by creating a separate dashboard.properties file within D:\Hygieia\api\ and  creating a separate github.properties file within D:\Hygieia\collectors\scm\github\. The API , UI and collectors run fine but have I installed it the right way or have I made a mistake?

**Comment by Dinnerspy** [comment]
sound good to me.

**Comment by matthewbeasley** [comment]
@Avfdo1994 - it's totally up to you where you put your properties file and up to you whether you use a single file or not. The command line arg '--spring.config.prefix' used when starting up the jar tells you which properties to use in the specified file. 

Personally, since I often destroy and reclone my repo I have my properties files in a centralized location that is not in the project. I recommend this if you plan to work on the project since it will keep your `git status` clean. Mine are in `~/dev/config/`. @satishc1 recommended this to me and it's worked great so far.

**Comment by Avfdo1994** [comment]
@matthewbeasley so just to be clear --spring.config.prefix does not refer to the file name say for example --spring.config.prefix=bitbucket means it looks for a properties file that's named bitbucket.properties?

**Comment by Dinnerspy** [comment]
@Avfdo1994 the --spring.config.location= tells it what properties to use.
