### ISSUE TITLE
Hygieia Capacity Planning

### ISSUE THREAD

**Issue by venkiradkris** [capitalone/Hygieia#2144]
Hi
We need to plan to setup Hygieia to build dashboard for 25 application level CI/CD pipelines.
Any idea / inputs regarding Linux Server Capacity? In future we might need to scale it to increase the number of application dashboards.
Please suggest.
Regards
Venkat

**Comment by venkiradkris** [comment]
Hi - Can anyone help? Thanks.

**Comment by matthewbeasley** [comment]
@venkiradkris - are you planning to host all components of hygieia on a single server?

**Comment by venkiradkris** [comment]
Hi - We need suggestion how best we can do deployment.
My thoughts.
Option [1]
a) Keeping Dashboard, MongoDB in one server
b) Keeping all collectors in one server
Option [2]
a) Keeping Dashboard, MongoDB in one server
b) Keeping all collectors respective component server (Ex) keeping jenkin collector where jenkins is running, keeping sonar collector where sonar is running etc
For both the options, need to know about Linux Server Capacity need.
Please help. Thanks.

**Comment by venkiradkris** [comment]
Option [3]
Is it advisable to keep all components of (Collectors, Dashboard, MongoDB) in single server? If so, how about Linux Server Capacity?

**Comment by venkiradkris** [comment]
Hi - Any update/help? Thanks.

**Comment by matthewbeasley** [comment]
@venkiradkris - It's very difficult to quote you a server capacity because your required capacity will depend on your load which will depend on how much you use Hygieia. Your "dashboard for 25 application level CI/CD pipelines." is fairly minimal so you could get away with putting all components on a single server with dual core cpu and 4gb of ram. As your use grows the very first thing I would do is separate the db and everything else. Second step would be to split out the collectors but I doubt you'll ever need to do that.

**Comment by matthewbeasley** [comment]
@venkiradkris - reach out to us on gitter.im if you have further questions.
