### ISSUE TITLE
Containers for the collectors

### ISSUE THREAD

**Issue by jimzucker** [capitalone/Hygieia#227]
Today there are not containers for collectors, I am going to create a branch and create containers for my use and send in a pull request to see if they are accepted by the project (I am new to working on open source projects so I hope I am following the correct protocol).

I plan to create a container for each collector, if there is a different idea please share it with me.  Ian also going to create config scripts for each one based on the readme files.

**Comment by softwareklinic** [comment]
Won't the container be heavy or probably over-engineering for collectors ?  Just curious and Sharing my thought... Especially per collector basis might be



Regards,
Keyur

On Dec 16, 2015, at 1:20 PM, Jim Zucker <notifications@github.com<mailto:notifications@github.com>> wrote:


Today there are not containers for collectors, I am going to create a branch and create containers for my use and send in a pull request to see if they are accepted by the project (I am new to working on open source projects so I hope I am following the correct protocol).

I plan to create a container for each collector, if there is a different idea please share it with me. Ian also going to create config scripts for each one based on the readme files.

**Comment by jimzucker** [comment]
I agree with upur points but testing and grtti g the project up and running today is alot of steps.

Ill get the containers all working and then based on feedback i could repackage it

- maybe deploy on one of the existig containers?  Or all in one new container?

The goal is to make bringing up the whole stack easily

Make sense?

**Comment by softwareklinic** [comment]
Absolutely, it makes perfect sense.

We were discussing during the team meeting today about the same,, since looks like in the current state of affairs, the dashboard can track
1 Branch of code… for any given project at this point… now if we want to track 2-3 branches of the same project… or 2-3 projects… with 3-4 container / branch it would be soon be a mess.

We need to look at 2 things

 1.  From infrastructure perspective – how soon we can have the env up and running
 2.  How do we manage/design it for future – since soon you will see lot of people adapting this tool and then how do you make this manageable for complex corporate applications.

We were thinking maybe a single container with all collectors + api + ui would be a good option for a given branch.. We can have tracking for any single branch of code up and running quickly…

Let me know your thoughts.


Keyur

**Comment by jimzucker** [comment]
OK, here is a working version of the githup, I creased a branch here as I am not approved to create branches on this project: https://github.com/jimzucker/hygieia.git

I think I set it up correctly so you can access it.

From you comment above I think it is implying currently have to run multiple git collectors for multiple branches, should it be a 1:M vs a 1:! process, that is probably a better path to have one process spin through all of the URLS configured on a dashboard.

Take a look, I can restructure the deployment based on the feedback form the team, I am looking at the other collectors now.

![screenshot 2015-12-16 15 25 20](https://cloud.githubusercontent.com/assets/14372687/11856984/7bf7ca3c-a409-11e5-9469-51fc24acd36b.png)

**Comment by tabladrum** [comment]
Ability to track multiple branches, builds etc are coming end of jan 2016. We are starting our dev first week of Jan.

**Comment by softwareklinic** [comment]
Great - that would be awesome.. Any blueprints that we can look and contribute any inputs / feedback



Regards,
Keyur

On Dec 16, 2015, at 6:05 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


Ability to track multiple branches, builds etc on the same dashboard are coming end of jan 2016. We are starting our dev first week of Jan.

**Comment by tabladrum** [comment]
Absolutely. Will publish shortly. Send in your input via issues.
