### ISSUE TITLE
Jira feature (features in progress list)

### ISSUE THREAD

**Issue by cfmaley** [capitalone/Hygieia#266]
What is the requirements for the features in progress list to get populated ?

Should all in progress issues appear for the current sprint? 

I have created a sprint and have associated tasks with that sprint. I've changed the  status to in progress but the features in progress list in not appearing. 

The sprint name and estimates for total, wip and done are being populated

**Comment by amp5208** [comment]
@cfmaley , thank you for reaching out regarding your Jira Feature question.  Currently, the "features in progress" content on the FeatureWidget are designed to pull the time-estimate located in the Jira out-of-the-box field called <strong></strong>.  This is then transformed in the following way so that the numbers are manageable on the display:

<pre>
// sEstimate, in seconds, converted to hours, rounded down:
// 8 hours = 1 day; 5 days = 1 week
String hours = "";
long seconds = 0;
try {
       seconds = (long) fields.get("timeestimate");
       hours = Integer.toString((int) (seconds / 3600));
       feature.setsEstimate(TOOLS.sanitizeResponse(hours));
       } catch (Exception e) {
              feature.setsEstimate("0");
       }
</pre>

Once data is transformed, "in progress" estimates are assumed based on the Jira <strong>statusCategory</strong> field, which is configured based on your Jira screen's workflow configuration.  You must have a statusCategory called "In Progress" - This can be modified by a user with <strong>Project Administrative</strong> access.  The following is the precise MongoDB query being used in code to get this information:

<pre>
@Query(value = " {'sTeamID' : ?0 , $and : [{'isDeleted' : 'False'} , {'sState' : 'Active'}] , $or : [{'sStatus' : 'In Progress'} , {'sStatus' : 'Waiting'} , {'sStatus' : 'Impeded'}] , $and : [{'sSprintID' : {$ne : null}} , {'sSprintBeginDate' : {$lte : ?1}} , {'sSprintEndDate' : {$gte : ?1}}]}, $orderby: { 'sStatus' :-1 }", fields = "{'sStatus': 1,'sEstimate' : 1}")
	List<Feature> getSprintBacklogInProgress(String sTeamID, String currentISODateTime);
</pre>

Please also note that the newest code in master allows for some custom configuration based on your Jira instance.  You should also provided the following property values based on your instance's configuration:

<pre>
. . .
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a numerical ID reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType ID
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
feature.jiraIssueTypeId=7
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10007
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10400
. . .
</pre>

Please let me know if you have any additional questions and if this issue can be resolved.

**Comment by amp5208** [comment]
@tabladrum , This issue can be closed, as it was resolved on a previous merge.  @cfmaley, please confirm if you have any open questions related to this issue.

**Comment by manjunath2008** [comment]
Hi All,

Can anyone please tell me how is the Done value in Hygieia dashboard is being computed.

Thanks & Regards
Manjunath

**Comment by amp5208** [comment]
@manjunath2008 , Thank you for reaching out regarding your question.  Currently, the Done value is calculated using either the Detail Estimate value (VersionOne) or the Remaining Estimate value (Jira) summed and rounded-down for any stories mapped to the following statuses:  Done, Accepted.  Let me know if you need more specific details.

**Comment by manjunath2008** [comment]
Hi,

Thanks for the response. I am using Jira collector, I have couple of questions
1) Can you please tell me what information is Jira widget in the dashboard is displaying.
2) What does numeric value above Total, WIP, Done indicate

Thanks & Regards
Manjunath

**Comment by manjunath2008** [comment]
Hi, 

@amp5208 can you please answer these questions.

Thanks & Regards
Manjunath.V

**Comment by amp5208** [comment]
@manjunath2008 , Thank you for following-up.  I will answer your questions below:

1. _Can you please tell me what information is Jira widget in the dashboard is displaying._ The feature widget will display Jira's **Remaining Estimate sums for stories** of a given active team/sprint combo selected by the end-user under the following status categories:  **All Active (_Total_), In Progress (_WIP_), Done**.  As Remaining Estimate is depleted, the sums will also deplete.  These are not counts of stories, but instead based on the out-of-the-box Jira burn-down features on issues-type-story.  See my answer above for more detail:  https://github.com/capitalone/Hygieia/issues/266#issuecomment-209667297
2. _What does numeric value above Total, WIP, Done indicate_ See the answer I provided above.

Let me know if you have any further questions.

**Comment by ghouspasha** [comment]
@tabladrum :  In Jira feature collector I am facing a problem while passing issueType ID, I have passed strory as IssueType Id in application.prop and I am receiving objects for bug, support and sub-tasks along with story. Could you please share any documentation related to this collector?

**Comment by amp5208** [comment]
@ghouspasha , Thank you for reaching out.  Please make sure that your property is listed precisely as follows:

```properties
feature.jiraIssueTypeId=Story
```

Let me know if you are still seeing issues after ensuring this configuration.  All other configuration details are listed in the [README](https://github.com/capitalone/Hygieia/blob/master/jira-feature-collector/README.md), although I will be simplifying the configuration details shortly.

**Comment by amp5208** [comment]
@manjunath2008 , Please follow up and let me know if you have been successful in validating the following information:  https://github.com/capitalone/Hygieia/issues/266#issuecomment-215733119

**Comment by ashnaa** [comment]
Hi,
Is the Remaining Estimate sums for stories field is the accumulated value per end-user? Or is it across the active sprint ?

**Comment by ashnaa** [comment]
I am not able to get all the stories in my active sprint in Hygiea. Any pointers will be of help .

**Comment by amp5208** [comment]
@ashnaa , Thank you for reaching out.  The sums are based on accumulated value per team / active sprint.

Additionally, a new version of Hygieia's feature widget was released recently that included Kanban/Scrum simultaneous support (https://github.com/capitalone/Hygieia/pull/606).  Please pull the latest code and try with the new configuration.  Note that the properties required to run the collector have slightly changed - check the updated feature collector README for details.

**Comment by tabladrum** [comment]
Please use the latest master - a lot of enhancements and fixes have been made to feature widget.
