### ISSUE TITLE
Creating a user with less than 3 characters is allowed

### ISSUE THREAD

**Issue by bescott1** [capitalone/Hygieia#268]
Hygieia allows creation of a new username with less than 3 characters, however the login field validator expects a username to be at least 4.

When logging in with the valid 3 character user, the error message is: "Please fill all the form fields correctly". This message isn't helpful at all.

Either validate that a new user is at least 4 characters, or allow less than 4 characters when logging in.

**Comment by amitmawkin** [comment]
we will validate and let you know when a bug fix is released.

**Comment by bescott1** [comment]
Thanks for the quick response!

**Comment by bescott1** [comment]
If you'd like I could add the validation code and submit a pull request today

**Comment by amitmawkin** [comment]
Thanks for reporting it and for offering to contribute, I have provided a fix which would put the simple validation rules in sync.
If you would like to contribute further please fill our contribution form https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform
and review our UI layer . Also if your issue is resolved please close this issue

**Comment by bescott1** [comment]
Thank you for the fix.
