### ISSUE TITLE
Jenkins-Hygieia plugin and API for ingestion: Testers wanted

### ISSUE THREAD

**Issue by tabladrum** [capitalone/Hygieia#279]
Testers wanted: 
New API for data ingestion: https://github.com/capitalone/Hygieia/tree/hygieia-2.0
-- follow same build process for Hygieia

Hygieia-Jenkins plugin: https://github.com/tabladrum/hygieia-jenkins-plugin 
Instructions in Readme.

**Comment by softwareklinic** [comment]
What are the enhancements / blueprint for the same



Regards,
Keyur

On Jan 17, 2016, at 1:34 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


Testers wanted:
New API for data ingestion: https://github.com/capitalone/Hygieia/tree/hygieia-2.0
-- follow same build process for Hygieia

Hygieia-Jenkins plugin: https://github.com/tabladrum/hygieia-jenkins-plugin
Instructions in Readme.

**Comment by tabladrum** [comment]
As a part of Hygieia 2.0, we are creating a pipeline to track commits all the from commit stage to production. In order to do this seamlessly we need to create links that are missing today. So, we will be going away (as much as possible) from running collectors and rather accept event data via plugins such as Jenkins plugin for Hygieia. I will publish some great details next week.

**Comment by softwareklinic** [comment]
Ty  - will be able to help test



Regards,
Keyur

On Jan 17, 2016, at 8:02 PM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


As a part of Hygieia 2.0, we are creating a pipeline to track commits all the from commit stage to production. In order to do this seamlessly we need to create links that are missing today. So, we will be going away (as much as possible) from running collectors and rather accept event data via plugins such as Jenkins plugin for Hygieia. I will publish some great details next week.

**Comment by tabladrum** [comment]
We tested it internally. Closing this.

**Comment by gThiru** [comment]
Hi 
i have configured hygieia-jenkins-plugin but nothing is reflected in Hygieia dashboard :-1:
