### ISSUE TITLE
will it be any collector for CA LISA Service Virtualization?

### ISSUE THREAD

**Issue by daniuniperu** [capitalone/Hygieia#289]
Please anyone who has implemented a collector for CA LISA Service Virtualization? 

Or maybe any ideas how to start this collector?

**Comment by tabladrum** [comment]
Not that we are aware of. What do you want to capture and display from Lisa?

**Comment by daniuniperu** [comment]
The steps on the collector side would be:

1.	the URL  from Lisa Application returns an XML file which must be converted to JSON format. 
2.	Save the JSON formatted data in MongoDB.

Then on the GUI side, it would be to place CA LISA data in modified Monitor widget:

1.	In Configuration modal dialog let user choose GroupTag 
2.	In the widget display table of ModelName and UpTime form de JSON Format.

please any ideas. would be really apreciated

**Comment by daniuniperu** [comment]
Any Ideas please?

**Comment by vishalbisa** [comment]
Hi @daniuniperu 

Ideas for above queries : 

1) From the collector prespective you can use XML parser to parse your xml file , by adding Jsoup jar files as your project reference (change pom.xml file so that while building it would take care ).

2) after XML parsing the same collector code can be re-used for saving data in DB.

GUI.
1) Since you are using monitor widget, you can server list by adding the environment details, i dont see any way to choose GroupTag or you can create a dropdown and fetch those details from an external API where the GroupTag are shown.

2) once you parse the xml data from collector code, save your details which you want to display.
you can modify the view.js file accordingly to fetch the details as you would be creating a new API with new enum.

Thanks,
Vishal

**Comment by satishc1** [comment]
Closed. No plans to write this collector atm.
