### ISSUE TITLE
Hygieia integration with HP Fortify

### ISSUE THREAD

**Issue by jutiad** [capitalone/Hygieia#554]
Hi, I was reading about integrating Fortify collector. 
Is there any example of how to do it?
I had already configured Jira,Stash,Jenkins,Lisa and Sonar, just missing Fortify. I just read that this data should appear on Security Analysis section of Quality Widget.

![listjobs](https://cloud.githubusercontent.com/assets/19315208/15197928/e1cc6526-1799-11e6-94d0-97205be5c384.png)

**Comment by tabladrum** [comment]
We could not publish the fortify collector as open source because it had to use some libraries that are commercially licensed. I have keep that that collector under my github account - you are free to get the code - it is public. To build it successfully you will need those commercial jar files.

**Comment by jutiad** [comment]
Yeah, suppose I have them, how do  I run it?, with the other collectors .. for example Jira .. I do the next steps:
1. Configure properties file so it can read MongoDB
2. Run jar as for example: 
    java -jar target\jira-feature-collector.jar
3. Open Hygieia and see the results

**Comment by jutiad** [comment]
sorry to ask again, is there any video available to know how to run the HP Fortify Collector with Hygieia? 
Thanks,
Jose

**Comment by tabladrum** [comment]
We did not put that in the video. However, if you know how to run the other collectors, you run the fortify collector the same way. On the UI, the Fortify projects should show up after the first run of the collector. What commands are you using to run the collector?

**Comment by jutiad** [comment]
Hi,
for example, for Jira collector, in the jira-collector folder I run the following:

C:\Hygieia\jira-feature-collector>java -jar target\jira-feature-collector.jar

**Comment by tabladrum** [comment]
Should be exactly the same approach. Did you build the fortify project successfully?

**Comment by jutiad** [comment]
But in another posts, you said that we need to have 
com.fortify:fortify-common:jar:4.30,
com.fortify:fortify-crypto:jar:1.0,
com.fortify:fortify-meta-api:jar:4.30,
com.fortify:fortify-meta-impl:jar:4.30,
com.fortify:fortify-public:jar:4.30,
com.sun.xml.wsit:xws-security:jar:1.3.1,
com.sun.xml.wsit:wsit-rt:jar:1.1,
com.fortify:wsclient:jar:4.30,
com.fortify:wsobject:jar:4.30,

But when running, which jar should be used?

**Comment by dkpurushothaman** [comment]
i have build the fortify collector successfully , i have some queries regarding data collection, i have installed fortify static code analyzer in local machine , what need to be configure to application properties.

**Comment by tabladrum** [comment]
Please re-open if you have further questions.

**Comment by tinabear** [comment]
@tabladrum is it possible to directly send json to api with security check result by Veracode? Just like what I am doing for deployment. Thank you.

**Comment by arunmk108** [comment]
> i have build the fortify collector successfully , i have some queries regarding data collection, i have installed fortify static code analyzer in local machine , what need to be configure to application properties.

Hi Purushotham,
Need small information on fortify. Can you share your number please. 
My mail id: mail2arunmk@gmail.com

**Comment by dkpurushothaman** [comment]
9094848542, can you please share the plugin

Sent from Yahoo Mail on Android 
 
  On Tue, 18 Sep 2018 at 8:44 PM, arunmk108<notifications@github.com> wrote:   

i have build the fortify collector successfully , i have some queries regarding data collection, i have installed fortify static code analyzer in local machine , what need to be configure to application properties.


Hi Purushotham,
Need small information on fortify. Can you share your number please.
My mail id: mail2arunmk@gmail.com

**Comment by arunmk108** [comment]
@tabladrum, I have added all dependency jars(pasted below) .m2 directory after cloning your code and built the code with success status.

fortify-common-18.10.0.0187.jar, fortify-crypto-1.0.jar, fortify-meta-api-18.10.0.0187.jar, fortify-meta-impl-18.10.0.0187.jar, fortify-public-18.10.0.0187.jar, wsclient-18.10.0187.jar, wsobjects-18.10.0.0187.jar, activation-1.1.1.jar, serializer-2.7.1.jar

When iam starting collector api, getting below error. Can you suggest what could be the issue to this. We are using fortify 18.10 version and hygieia 2.0.5. 

[root@awsdldashboard02 target]# java -jar fortify-collector-1.0.jar --spring.config.name=fortify.properties --spring.config.location=/vol/hygieia/Hygieia/collectors/fortify-collector/fortify.properties &
[1] 371
[root@awsdldashboard02 target]# java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/Banner$Mode
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:158)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:98)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:64)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
        at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:100)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:59)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:286)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:969)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:958)
        at com.capitalone.dashboard.Application.main(Application.java:14)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.Banner$Mode
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:177)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:143)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by arunmk108** [comment]
continuation to above one.
Pasting the build logs also here for your reference.

[root@awsdldashboard02 fortify-collector]# mvn clean install package
[INFO] Scanning for projects...
[INFO]
[INFO] -------------< com.capitalone.dashboard:fortify-collector >-------------
[INFO] Building fortify-collector 1.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from codehaus: http://repository.codehaus.org/org/codehaus/woodstox/stax2-api/maven-metadata.xml
[WARNING] Could not transfer metadata org.codehaus.woodstox:stax2-api/maven-metadata.xml from/to codehaus (http://repository.codehaus.org): repository.codehaus.org: Name or service not known
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ fortify-collector ---
[INFO] Deleting /vol/hygieia/Hygieia/collectors/fortify-collector/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ fortify-collector ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /vol/hygieia/Hygieia/collectors/fortify-collector/src/main/resources
[INFO] skip non existing resourceDirectory /vol/hygieia/Hygieia/collectors/fortify-collector/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ fortify-collector ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 24 source files to /vol/hygieia/Hygieia/collectors/fortify-collector/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ fortify-collector ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /vol/hygieia/Hygieia/collectors/fortify-collector/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ fortify-collector ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ fortify-collector ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ fortify-collector ---
[INFO] Building jar: /vol/hygieia/Hygieia/collectors/fortify-collector/target/fortify-collector-1.0.jar
[INFO]
[INFO] --- spring-boot-maven-plugin:1.2.7.RELEASE:repackage (default) @ fortify-collector ---
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ fortify-collector ---
[INFO] Installing /vol/hygieia/Hygieia/collectors/fortify-collector/target/fortify-collector-1.0.jar to /vol/hygieia/.m2/repository/com/capitalone/dashboard/fortify-collector/1.0/fortify-collector-1.0.jar
[INFO] Installing /vol/hygieia/Hygieia/collectors/fortify-collector/pom.xml to /vol/hygieia/.m2/repository/com/capitalone/dashboard/fortify-collector/1.0/fortify-collector-1.0.pom
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ fortify-collector ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /vol/hygieia/Hygieia/collectors/fortify-collector/src/main/resources
[INFO] skip non existing resourceDirectory /vol/hygieia/Hygieia/collectors/fortify-collector/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ fortify-collector ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ fortify-collector ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /vol/hygieia/Hygieia/collectors/fortify-collector/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ fortify-collector ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ fortify-collector ---
[INFO] No tests to run.
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO]
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ fortify-collector ---
[INFO]
[INFO] --- spring-boot-maven-plugin:1.2.7.RELEASE:repackage (default) @ fortify-collector ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.676 s
[INFO] Finished at: 2018-09-25T15:46:05-04:00
[INFO] ------------------------------------------------------------------------

**Comment by dkpurushothaman** [comment]
Some jar versions. Getting conflicting

Sent from Yahoo Mail on Android 
 
  On Wed, 26 Sep 2018 at 1:20 AM, arunmk108<notifications@github.com> wrote:   
continuation to above one.
Pasting the build logs also here for your reference.

[root@awsdldashboard02 fortify-collector]# mvn clean install package
[INFO] Scanning for projects...
[INFO]
[INFO] -------------< com.capitalone.dashboard:fortify-collector >-------------
[INFO] Building fortify-collector 1.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from codehaus: http://repository.codehaus.org/org/codehaus/woodstox/stax2-api/maven-metadata.xml
[WARNING] Could not transfer metadata org.codehaus.woodstox:stax2-api/maven-metadata.xml from/to codehaus (http://repository.codehaus.org): repository.codehaus.org: Name or service not known
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ fortify-collector ---
[INFO] Deleting /vol/hygieia/Hygieia/collectors/fortify-collector/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ fortify-collector ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /vol/hygieia/Hygieia/collectors/fortify-collector/src/main/resources
[INFO] skip non existing resourceDirectory /vol/hygieia/Hygieia/collectors/fortify-collector/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ fortify-collector ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 24 source files to /vol/hygieia/Hygieia/collectors/fortify-collector/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ fortify-collector ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /vol/hygieia/Hygieia/collectors/fortify-collector/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ fortify-collector ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ fortify-collector ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ fortify-collector ---
[INFO] Building jar: /vol/hygieia/Hygieia/collectors/fortify-collector/target/fortify-collector-1.0.jar
[INFO]
[INFO] --- spring-boot-maven-plugin:1.2.7.RELEASE:repackage (default) @ fortify-collector ---
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ fortify-collector ---
[INFO] Installing /vol/hygieia/Hygieia/collectors/fortify-collector/target/fortify-collector-1.0.jar to /vol/hygieia/.m2/repository/com/capitalone/dashboard/fortify-collector/1.0/fortify-collector-1.0.jar
[INFO] Installing /vol/hygieia/Hygieia/collectors/fortify-collector/pom.xml to /vol/hygieia/.m2/repository/com/capitalone/dashboard/fortify-collector/1.0/fortify-collector-1.0.pom
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ fortify-collector ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /vol/hygieia/Hygieia/collectors/fortify-collector/src/main/resources
[INFO] skip non existing resourceDirectory /vol/hygieia/Hygieia/collectors/fortify-collector/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ fortify-collector ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ fortify-collector ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /vol/hygieia/Hygieia/collectors/fortify-collector/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ fortify-collector ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ fortify-collector ---
[INFO] No tests to run.
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO]
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ fortify-collector ---
[INFO]
[INFO] --- spring-boot-maven-plugin:1.2.7.RELEASE:repackage (default) @ fortify-collector ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.676 s
[INFO] Finished at: 2018-09-25T15:46:05-04:00
[INFO] ------------------------------------------------------------------------
