### ISSUE TITLE
Product Dashboard

### ISSUE THREAD

**Issue by Venkattk** [capitalone/Hygieia#593]
Hi,

I am trying to add 1 more stage called **Feature** to display the Sprint details(from Jira) in the Product dashboard UI. Could you please give some inputs on this i.e how to fetch the data from MongoDB and display?

//Public properties
ctrl.stages = ['commit', 'Build', '**Feature**', 'Dev', 'QA', 'Int', 'Perf', 'Prod'];

**Comment by tabladrum** [comment]
One problem (due to which we stayed away from doing this in the current version) is to relate the features to commits. Tagging each commit with Jira ticket etc is not full proof - developers may not follow the practice all the time. Also, it is hard to conclusively determine if a feature is in the pipeline. Feature branching may be helpful but still not conclusive. I am very much open to ideas.

**Comment by Venkattk** [comment]
I understood the reason, I will think about the same & come back. In the mean time I just want to display the active sprint name, WIP, Total values as displayed in team dashboard without relating them with builds & commits. please let me know how it could be displayed in product dashboard UI?

**Comment by satishc1** [comment]
Closed.
