### ISSUE TITLE
Confusion on Stash/Bitbucket implementations

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#609]
Hello,

I am trying to get the stash scm collector up and running and am confused. For starters, Atlassian rebranded "stash" as "BitBucket Server." Going through the debugger it appears that hitting our "bitbucket" server results in the DefaultBitbucketClient being used in code. However I am getting back responses that use "id" instead of "hash", "name" instead of "raw" and "authorTimestamp" instead of "date". This corresponds to the stash api documented here: https://developer.atlassian.com/static/rest/stash/3.11.3/stash-rest.html#idp1513136 and is shown below.

Now it appears that the code for DefaultStashClient has the implementation that will understand this response. However, that class is not annotated with @Component and so isn't wired in.

So I have a few questions:

- How can I use the DefaultStashClient?
- Why does the "Bitbucket" client look for different json tags? Did the api change? Does it correspond to "Bitbucket" (not stash) before they were merged?
- What should I do to get this working?

```
{
    "size": 1,
    "limit": 25,
    "isLastPage": true,
    "values": [
        {
            "id": "def0123abcdef4567abcdef8987abcdef6543abc",
            "displayId": "def0123abcd",
            "author": {
                "name": "charlie",
                "emailAddress": "charlie@example.com"
            },
            "authorTimestamp": 1442553509156,
            "message": "More work on feature 1",
            "parents": [
                {
                    "id": "abcdef0123abcdef4567abcdef8987abcdef6543",
                    "displayId": "abcdef0"
                }
            ]
        }
    ],
    "start": 0,
    "authorCount": 1,
    "totalCount": 1
}
```

**Comment by MarkRx** [comment]
Seems these questions remain unanswered from #189 

Tagging people who might know: @jdamick @dianewalls @srid99

**Comment by tabladrum** [comment]
@MarkRx we don't use BitBucket or Stash. It was contributed by @srid99 and et al. I know there are some confusions around the API and when these two came together. If you can help me with the research (such as API discrepancies) I can make the changes.

**Comment by srid99** [comment]
@MarkRx reading my [own comments](https://github.com/capitalone/Hygieia/pull/189#issuecomment-161416159), I don't think the stash client ever worked or tested. As you can see in the comment, I mentioned that there are some mapping discrepancies. And all I remember is to split the collectors and have 2 separate collectors. Before doing that I wanted to make sure there are some test cases available and [made a pull request](https://github.com/capitalone/Hygieia/pull/256) for that and just now noticed that it isn't merged yet.

**Comment by tabladrum** [comment]
@MarkRx @srid99 will pull in the old PR. Let me check what happened. 
In the mean time I reached out to another organization who has a stash collector - a modified version from what we have here. I will get the source and do a PR. Give me a couple of days.

**Comment by MarkRx** [comment]
Doing a diff of the files reveals that the only real changes are:
```
					String sha = str(jsonObject, "hash");
					JSONObject authorObject = (JSONObject) jsonObject.get("author");
					String message = str(jsonObject, "message");
					String author = str(authorObject, "raw");
					long timestamp = new DateTime(str(jsonObject, "date")).getMillis();
```
vs
```
					String sha = str(jsonObject, "id");
					JSONObject authorObject = (JSONObject) jsonObject.get("author");
					String message = str(jsonObject, "message");
					String author = str(authorObject, "name");
					long timestamp = Long.valueOf(str(jsonObject,"authorTimestamp"));
```

I'm thinking I can just combine them by hitting a field in the first one first (for backwards compatibility to whatever api it is hitting) and if it is not found hitting a field from the second one.

I.E.
```
String sha = str(jsonObject, "hash");
if (sha == null) {
  sha = str(jsonObject, "id");
}
```

Once that is done the unused "Stash" class can be removed.

**Comment by MarkRx** [comment]
Ok I think I figured out what is going on.

There are two "bitbucket" apis:

- Bitbucket Cloud: https://confluence.atlassian.com/bitbucket/commits-or-commit-resource-389775478.html#commitsorcommitResource-GETacommitslistforarepositoryorcomparecommitsacrossbranches
- Bitbucket Server (used to be called Stash): https://developer.atlassian.com/static/rest/stash/3.11.3/stash-rest.html#idp1513136

I think DefaultBitbucketClient.java was supposed to use the bitbucket cloud api but is erroneously mixing them together. The rest URL endpoint it is hitting uses the Bitbucket Server format but the return data that it is processing is using the Bitbucket Cloud format. I think this was missed because it is possible to get the incorrect code to work against the bitbucket cloud server by setting the api in the config to "api/2.0/repositories/". The bitbucket cloud service will ignore the sha and since parameters and return all commits. If no branching is done then this defaults to returning 'master' (which is what the sha would have pointed to) and all commits (which may be the same as all commits since XXX date in the config).

If both API's are needed then it might make sense to separate them out into separate projects: bitbucket-cloud-scm-collector and bitbucket-server-scm-collector. Documentation can be added to explain what is going on.

If that makes sense I can look at making the needed changes tomorrow.

**Comment by MarkRx** [comment]
Note: Working on fix for clarity and to allow multiple implementations here: https://github.com/paychex/Hygieia/tree/bitbucket

**Comment by MarkRx** [comment]
Addressed with #631

**Comment by gowthamastute** [comment]
Assignees

No one assigned
Labels

None yet
Projects

None yet
Milestone

No milestone
Notifications

  Unsubscribe
You’re receiving notifications because you authored the thread.
1 participant

@gowthamastute
@gowthamastute
   
gowthamastute commented 29 minutes ago
Hi

When I run the Bitbucket collector it is automatically embedding "projects/repo" in middle of the URL, so I am getting 404 URL not found error.

My private Bitbucket URL is:
https://bitbucket.company.com/projects/PDC/repos/browse/.gitignore/commits?until=develop&limit=25

But the below URL is verified after executing collector to check for the commit so I am getting 404 not found error.

https://bitbucket.company.com/rest/api/1.0/projects/projects/repos/PDC/repos/browse/.gitignore/commits?until=develop&limit=25

URL embedded in between:
1./rest/api/1.0
2./projects/repo
The above stated is added in between my private URL. Please help me should I need to modify any file to rectify this error.

Property file:
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbusername=user
dbpassword=password
git.cron=0 0/5 * * * *
git.host=https://bitbucket.company.com
git.api=/rest/api/1.0/
git.username=username
git.password=password
git.key=hdqe40mYMhM9AemY9rgDiRfDIvepJb
github.key=hdqe40mYMhM9AemY9rgDiRfDIvepJb
git.commitThresholdDays=15
git.pageSize=25
git.product=server

I execute the below command
java -jar bitbucket-scm-collector-2.0.5-SNAPSHOT.jar --spring.config.location=/home/hygieiaconf/applicationbb.properties

Got output as:
2017-02-13 06:05:00,196 INFO c.c.d.collector.CollectorTask - Repo Count 2 0s
2017-02-13 06:05:00,196 INFO c.c.d.collector.CollectorTask - New Commits 0 0s
2017-02-13 06:05:00,196 INFO c.c.d.collector.CollectorTask - Finished 0s

Unable to get the commit count.

**Comment by KMedhansh** [comment]
@MarkRx @satishc1 

2017-04-17 16:07:02,460 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from https://bitbucket.org/rest/api/1.0/projects/testbusinesslens/repos/tes-hub_web_ui_repo/commits?until=businesslens_develop_UI&limit=25
org.springframework.web.client.HttpClientErrorException: 404 Not Found
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:570) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]

**Comment by Sjnahak** [comment]
Hi ,
can anyone help me with the issue https://github.com/Hygieia/hygieia-scm-bitbucket-collector/issues/27
