### ISSUE TITLE
Jira Collector not gathering data.

### ISSUE THREAD

**Issue by rohitstatic** [capitalone/Hygieia#686]
Hi,

Below is my JIRAproperties file.

```
#Database Name
database=dashboard
#Database HostName - default is localhost
dbhost=127.0.0.1
#Database Port - default is 27017
dbport=27017
#Database Username - default is blank
dbusername=db
dbpassword=dbpass

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=50

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000
# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 0/5 * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo


# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
feature.jiraProxyUrl=
feature.jiraProxyPort=
feature.jiraBaseUrl=http://jira.mmut.com/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64
feature.jiraCredentials=<<credentials given>>
# OAuth is not fully implemented; please blank-out the OAuth values:
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
#############################################################################
feature.jiraIssueTypeId=Story

#############################################################################
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10000

#############################################################################
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=
#############################################################################
# Internal Status Mappings - THESE SHOULD BE FILLED OUT FOR EVERY CUSTOM STATUS VALUE
# IN YOUR JIRA INSTANCE
#
# Use the following API call to get all of your status mappings:  http://jira.your.instance.com/rest/api/2/status/
#############################################################################
feature.todoStatuses[0]=To Do
feature.doingStatuses[0]=In Progress
feature.doneStatuses[0]=Done

# Status mappings, E.g.:
#
# feature.todoStatuses[0]=Open
# feature.todoStatuses[1]=Groom
# feature.todoStatuses[2]=Selected for Development
# feature.todoStatuses[3]=Backlog
# feature.todoStatuses[4]=Grooming
# feature.todoStatuses[5]=ToDo
# feature.todoStatuses[6]=To Do
# feature.todoStatuses[6]=Backlog1
# feature.doingStatuses[0]=Validation
# feature.doingStatuses[1]=Test
# feature.doingStatuses[2]=In Process
# feature.doingStatuses[3]=In Progress
# feature.doingStatuses[4]=Awaiting Approval - 2
# feature.doingStatuses[5]=Change Request - 2
# feature.doneStatuses[0]=Awaiting Approval
# feature.doneStatuses[1]=Done
# feature.doneStatuses[2]=Resolved

```

I have given valid credentials and don't get a 403 etc. I could not get the value for feature.jiraEpicIdFieldName=  from the APIs but other values are sound. When I run the collector I get.

```
2016-07-12 12:50:00,023 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-07-12 12:50:00,080 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-12 12:50:00,080 INFO  c.c.d.collector.CollectorTask - http://jira.mmut.com/
2016-07-12 12:50:00,080 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-12 12:50:00,913 INFO  c.c.d.collector.CollectorTask - Team Data              59        0s
2016-07-12 12:50:01,480 INFO  c.c.d.collector.CollectorTask - Project Data           59        0s
2016-07-12 12:50:01,904 INFO  c.c.d.collector.CollectorTask - Story Data              0        0s
2016-07-12 12:50:01,905 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2016-07-12 12:55:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2016-07-12 12:55:00,002 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-12 12:55:00,002 INFO  c.c.d.collector.CollectorTask - http://jira.mmut.com/
2016-07-12 12:55:00,002 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-07-12 12:55:00,552 INFO  c.c.d.collector.CollectorTask - Team Data              59        0s
2016-07-12 12:55:00,973 INFO  c.c.d.collector.CollectorTask - Project Data           59        0s
2016-07-12 12:55:01,487 INFO  c.c.d.collector.CollectorTask - Story Data              1        0s
2016-07-12 12:55:01,487 INFO  c.c.d.collector.CollectorTask - Finished                         1s

```

And no sprint name, feature in progress gets populated. 

Any idea what is going wrong here. I have the latest code base

**Comment by tabladrum** [comment]
@MarkRx

**Comment by MarkRx** [comment]
What version of jira are you running?

Add logging to your sprint config to help track down what is going on. Either temporarily throw it into jira-properties-builder.sh or override the command for docker compose and point to a mounted properties file.

```
logging.level.com.capitalone.dashboard.collector=DEBUG
logging.level.com.capitalone.dashboard=DEBUG
```

**Comment by rohitstatic** [comment]
Logging does not show any error. 

My basic requirement is that for a project , I want to get the sprint name and categorize them into TO DO, WIP and DONE status. 

Can you please evaluate the above properties and comment whether it is enough for the above task.  The widget currently shows only the following.

![jira](https://cloud.githubusercontent.com/assets/661792/16794672/df9bd280-48f6-11e6-9098-0e8478785b5e.PNG)

Also I see that  the field `jiraIssueTypeId` can only be set to one value, but when I want to categorize into TO DO, WIP and DONE , then the type can be anything. 

Please guide me as to what minimum configuration needs to be done in order to make the above requirement work.

**Comment by MarkRx** [comment]
By changes do you mean config changes or code changes?

Regarding only picking up one issue type - yea I agree that should be changed to allow more than one. Looks like that will require a code change. Wound't be too hard so long as other issue types follow the same json format.

Depending on your setup the collector might not be collecting the timing estimate information from your system. PR #675 adds the ability to use story point metrics as well as improved timing metrics by trying two different fields for timing metric information so it can work with different setups.

**Comment by rohitstatic** [comment]
I see that the db has collected JIRA information for a team and the values for `sStatus` and `sState` is both `Done`. The issue falls in an active sprint but my Done coloumn shows zero. None of my sprints shows anything as done. 

My Properties file has doneStatuses mapped to the following.

```
feature.doneStatuses[0]=Closed
feature.doneStatuses[1]=Done
feature.doneStatuses[2]=Deployed
feature.doneStatuses[3]=Fixed
feature.doneStatuses[4]=Duplicate
```
Any help as to why my done field is not getting populated. Also the count of issues differ by a huge amount. Any help in troubleshooting it.

**Comment by rohitstatic** [comment]
I got it that the WIP , DONE etc are not counts but remaining estimates and makes sense. 
I have all I need hence I am closing this issue.

**Comment by MarkRx** [comment]
Correct. PR #682 adds the ability to report on story points and allows for collecting hour information on stories from another field.

**Comment by sneha127** [comment]
Hi,

Below is my JIRAproperties file.
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=******

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=../logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-01-01T00:00:00.000000
feature.masterStartDate=2016-01-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-01-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo
######################
# Trending Query need Number of Days After today to filter out Sprints which ends in future.
# This will used to filter Kanban project which has 20 years of Sprints
feature.sprintDays=60
# Trending Query also need Number of Days prior to look for Sprints which has already Ended
feature.sprintEndPrior=7
######################
#Scheduled Job prior minutes to recover data created during execution time
feature.scheduledPriorMin=2

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
feature.jiraProxyUrl=
feature.jiraProxyPort=
feature.jiraBaseUrl=https://jira.xxxx.com
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64
feature.jiraCredentials="gave my credentials in base64 format"
# OAuth is not fully implemented; please blank-out the OAuth values:
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
#############################################################################
feature.jiraIssueTypeId=bug

#############################################################################
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10005

#############################################################################
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=

#############################################################################
# In Jira, your instance will have its own custom field created for "story points"
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
#feature.jiraStoryPointsFieldName=
#feature.jiraProjectId=
#Core Artifacts
# These arrays of status mappings must be completed in order for custom source system statuses to be providable by
# Hygieia.  Currently, Hygieia only maps to the following 3 status mappings:  to do, doing, and done.  You can find
# all available issue status mappings by going to your instance's version of the following API call:
# http://fake.jira.com/rest/api/2/status/.  Your statuses are listed in the JSON response as "name."
feature.todoStatuses[0]=To Do
feature.doingStatuses[0]=In Progress
feature.doneStatuses[0]=Done

I would like to take the data for the issueType =bug.Though i have provided the property "feature.jiraIssueTypeId" as bug i am not getting any data related to it. Please let  me know is there any way i can fetch data related to only the "bugs".

**Comment by MarkRx** [comment]
feature.jiraIssueTypeId will be the system id (something like custom_xxxxx) of the field containing the issue type. "bug" is not a valid id.

**Comment by sneha127** [comment]
Thank you MarkRx for your reply.
 I have modified the property feature.jiraIssueTypeId to the id value returned by the rest call "https://[your-jira-domain-name]/rest/api/2/issuetype/". the id value for the bug was returned as "1". I updated the same value , but still i am not able to fetch the bug data. 

Below is the response which i am getting:
2017-02-15 17:42:21,913 INFO  c.c.d.collector.CollectorTask - Project Data
   1055        8s
2017-02-15 17:42:47,650 ERROR c.c.d.collector.FeatureCollectorTask - Failed to c
ollect jira information
java.lang.RuntimeException: java.net.SocketTimeoutException
        at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[gu
ava-14.0.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.ap
ply(DefaultHttpClient.java:256) ~[atlassian-httpclient-apache-httpcomponents-0.1
3.2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.ap
ply(DefaultHttpClient.java:249) ~[atlassian-httpclient-apache-httpcomponents-0.1
3.2.jar!/:na]
        at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:276)
~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
        at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:272)
~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
        at com.atlassian.util.concurrent.Promises$2.onFailure(Promises.java:167)
 ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1145) ~[
guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorSer
vice.execute(MoreExecutors.java:293) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.
execute(ExecutionList.java:150) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList
.java:135) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.AbstractFuture.setException(Abstrac
tFuture.java:203) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.SettableFuture.setException(Settabl
eFuture.java:68) ~[guava-14.0.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseH
ttpPromiseAsyncClient$1$2.run(SettableFuturePromiseHttpPromiseAsyncClient.java:5
9) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseH
ttpPromiseAsyncClient$ThreadLocalDelegateRunnable$1.run(SettableFuturePromiseHtt
pPromiseAsyncClient.java:197) ~[atlassian-httpclient-apache-httpcomponents-0.13.
2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseH
ttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.j
ava:90) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseH
ttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpP
romiseAsyncClient.java:192) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.
jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na
:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [n
a:1.8.0_121]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]
Caused by: java.net.SocketTimeoutException: null
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsy
ncRequestExecutor.java:279) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.client.LoggingAsyncRequestExecutor.timeout(L
oggingAsyncRequestExecutor.java:128) ~[httpasyncclient-4.0-beta3-atlassian-1.jar
!/:4.0-beta3-atlassian-1]
        at org.apache.http.impl.nio.DefaultHttpClientIODispatch.onTimeout(Defaul
tHttpClientIODispatch.java:136) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.DefaultHttpClientIODispatch.onTimeout(Defaul
tHttpClientIODispatch.java:50) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractI
ODispatch.java:169) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIO
Reactor.java:257) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(Abstr
actIOReactor.java:494) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor
.java:207) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIO
Reactor.java:284) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.
java:106) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.
run(AbstractMultiworkerIOReactor.java:604) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
        ... 1 common frames omitted

Jira Property values i used: 
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=../logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-01-01T00:00:00.000000
feature.masterStartDate=2016-01-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-01-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo
######################
# Trending Query need Number of Days After today to filter out Sprints which ends in future.
# This will used to filter Kanban project which has 20 years of Sprints
feature.sprintDays=60
# Trending Query also need Number of Days prior to look for Sprints which has already Ended
feature.sprintEndPrior=7
######################
#Scheduled Job prior minutes to recover data created during execution time
feature.scheduledPriorMin=2

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
feature.jiraProxyUrl=
feature.jiraProxyPort=
feature.jiraBaseUrl=https://jira.xxx.com
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64
feature.jiraCredentials=xxxx
# OAuth is not fully implemented; please blank-out the OAuth values:
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

feature.jiraIssueTypeId=1
feature.jiraSprintDataFieldName=customfield_10005
feature.jiraEpicIdFieldName=


#feature.jiraStoryPointsFieldName=
#feature.jiraProjectId=

feature.todoStatuses[0]=To Do
feature.doingStatuses[0]=In Progress
feature.doneStatuses[0]=Done


Please help me with this. Thank you

**Comment by MarkRx** [comment]
Disregard my last comment. If you are using the latest code the field name is now called feature.jiraIssueTypeNames. Here is an example:

> feature.jiraIssueTypeNames=Story,Bug,Defect,Spike,Tracker

**Comment by sneha127** [comment]
Hi Mark,
Thank you for the reply. Sorry for the delay in response as i was caught up in some project work.
Once i try this solution i will let you know of my status.

**Comment by sneha127** [comment]
Hi Mark,

Took the latest code and made the modification to the jira properties file as suggested by you,but still  i am getting the same error. I have attached the logs and the properties file below.

[jira-Properties.docx](https://github.com/capitalone/Hygieia/files/810599/jira-Properties.docx)

[Jira-Log.docx](https://github.com/capitalone/Hygieia/files/810581/Jira-Log.docx)

**Comment by MarkRx** [comment]
> java.lang.RuntimeException: java.net.SocketTimeoutException

You are having issues hitting jira. It could be a bad url or the server is simply too slow. Try reducing the page size:

> feature.pageSize=25

**Comment by sneha127** [comment]
Hi Mark,

As suggested i have changed the pageSize value to 25, still i am getting the same exception.
I have few questions:
1) Is it compulsory to give the epic id to collect the data?
2)Can we get the component wise bug details ? if yes,how can i do this?

Thank you for your support on this.

**Comment by MarkRx** [comment]
You will have to upload non-docx files (such as plain txt). The account used to gather information will need full access to the jira server. Issues do not need to have an epic set. There is no way to get finer grained bug details.

**Comment by sneha127** [comment]
Hi Mark,

This is the exception that i am getting while fetching the jira bug details: 
2017-03-06 13:14:20,094 ERROR o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-53 [CLOSED] HTTP protocol exception: null
java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(Unknown Source) ~[na:1.8.0_121]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[na:1.8.0_121]
