### ISSUE TITLE
Dependency failure for Building Hygieia Publisher Plugin 1.3-SNAPSHOT

### ISSUE THREAD

**Issue by beardaintweird** [capitalone/Hygieia#695]
Off of a fresh clone of Hygieia, we're seeing problems building the jenkins plugin. Here's our stack trace after `mvn clean package`: 

```sh
> mvn clean package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jenkins-ci.plugins:hygieia-publisher:hpi:1.3-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:1.3-SNAPSHOT (/Users/ujc428/Hygieia/hygieia-jenkins-plugin/pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13
[WARNING] 'build.plugins.plugin.version' for org.jacoco:jacoco-maven-plugin is missing. @ line 166, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Hygieia Publisher Plugin 1.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
....
[INFO] Final Memory: 24M/439M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve dependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:1.3-SNAPSHOT: Could not find artifact com.-removed-.dashboard:core:jar:2.0.2-SNAPSHOT in anonymous (https://nexus.kdc.-removed-.com/nexus/content/groups/CLM) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by tabladrum** [comment]
Clone Hygieia root. mvn clean install and then build the plugin. We have not released core 2.0.2 yet. We will most probably move this plugin to jenkins plugin repo.

**Comment by beardaintweird** [comment]
Received this error after running `mvn clean install` in core:
```sh
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.capitalone.dashboard:Hygieia:2.0.2-SNA
PSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-
parent:pom:1.2.5.RELEASE from/to central (https://repo.maven.apache.org/maven2):
 Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.32.215] fai
led: Connection timed out: connect and 'parent.relativePath' points at wrong loc
al POM @ com.capitalone.dashboard:Hygieia:2.0.2-SNAPSHOT, C:\Users\Gur648\Hygiei
a\pom.xml, line 10, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.capitalone.dashboard:core:[unknown-version] (C:\Users\
Gur648\Hygieia\core\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.capitalone.dashboard:Hygieia:2.0.2
-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-star
ter-parent:pom:1.2.5.RELEASE from/to central (https://repo.maven.apache.org/mave
n2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.32.215]
 failed: Connection timed out: connect and 'parent.relativePath' points at wrong
 local POM @ com.capitalone.dashboard:Hygieia:2.0.2-SNAPSHOT, C:\Users\Gur648\Hy
gieia\pom.xml, line 10, column 10 -> [Help 2]

**Comment by beardaintweird** [comment]
Got a previously created HPI file for the jenkins plugin I needed to set up from @tabladrum

**Comment by summit123** [comment]
Hi I am still getting the error after re-cloning Hygieia -> mvn clean install and building hygieia jenkins plugin. 

mvn clean install from /hygieia-jenkins-plugin folder

[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.106 is missing, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:hygieia-publisher:hpi:1.4-SNAPSHOT
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jenkins-ci.plugins:hygieia-publisher:hpi:1.4-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:1.4-SNAPSHOT (/home/svc-hygieia/node/mtvgserver001_sdt-ecomp-portal/workspace/Hygieia/hygieia-jenkins-plugin/pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13
[WARNING] 'build.plugins.plugin.version' for org.jacoco:jacoco-maven-plugin is missing. @ line 185, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Hygieia Publisher Plugin 1.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-install-plugin/2.3.1/maven-install-plugin-2.3.1.pom
Downloaded: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-install-plugin/2.3.1/maven-install-plugin-2.3.1.pom (5 KB at 15.1 KB/sec)
Downloading: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-install-plugin/2.3.1/maven-install-plugin-2.3.1.jar
Downloaded: http://repo.jenkins-ci.org/public/org/apache/maven/plugins/maven-install-plugin/2.3.1/maven-install-plugin-2.3.1.jar (23 KB at 114.6 KB/sec)
Downloading: http://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/1.567/jenkins-war-1.567-war-for-test.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:10 min
[INFO] Finished at: 2016-09-12T17:37:26+00:00
[INFO] Final Memory: 24M/378M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve dependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:1.4-SNAPSHOT: Could not transfer artifact org.jenkins-ci.main:jenkins-war:jar:war-for-test:1.567 from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/): GET request of: org/jenkins-ci/main/jenkins-war/1.567/jenkins-war-1.567-war-for-test.jar from repo.jenkins-ci.org failed: Premature end of Content-Length delimited message body (expected: 68151300; received: 23435919 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by kavitha0624** [comment]
Just cloned Hygieia master in STS. Receiving this error after mvn compile:

[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.2.5.RELEASE/spring-boot-starter-parent-1.2.5.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.capitalone.dashboard:Hygieia:2.0.4-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.5.RELEASE from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.44.215] failed: Connection timed out: connect and 'parent.relativePath' points at wrong local POM @ line 14, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.capitalone.dashboard:Hygieia:2.0.4-SNAPSHOT (C:\Workspace\Hygieia\Hygieia_Master\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.capitalone.dashboard:Hygieia:2.0.4-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.5.RELEASE from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.44.215] failed: Connection timed out: connect and 'parent.relativePath' points at wrong local POM @ line 14, column 11 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Please help. I see that the above issue is similar to this but not finding solution for this on this page.

**Comment by anshul14** [comment]
Cloned Hygieia master on my local machine and when I try to do mvn clean install I get the following error:
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.2.5.RELEASE/spring-boot-starter-p                                  arent-1.2.5.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.capitalone.dashboard:Hygieia:2.0.4-SNAPSHOT: Could not transfer artifact org.springframework.bo                                  ot:spring-boot-starter-parent:pom:1.2.5.RELEASE from/to central (https://repo.maven.apache.org/maven2): Failed to transfer file: https://                                  repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.2.5.RELEASE/spring-boot-starter-parent-1.2.5.RELEASE.p                                  om. Return code is: 400 , ReasonPhrase:Bad Request. and 'parent.relativePath' points at wrong local POM @ line 14, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.capitalone.dashboard:Hygieia:2.0.4-SNAPSHOT (C:\Anshul_Saxena\Work\Experiments\Hygieia\Hygieia\pom.xml) has 1 e                                  rror
[ERROR]     Non-resolvable parent POM for com.capitalone.dashboard:Hygieia:2.0.4-SNAPSHOT: Could not transfer artifact org.springframewor                                  k.boot:spring-boot-starter-parent:pom:1.2.5.RELEASE from/to central (https://repo.maven.apache.org/maven2): Failed to transfer file: http                                  s://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.2.5.RELEASE/spring-boot-starter-parent-1.2.5.RELEA                                  SE.pom. Return code is: 400 , ReasonPhrase:Bad Request. and 'parent.relativePath' points at wrong local POM @ line 14, column 11 -> [Help                                   2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Does anyone know the cause of this? Tried researching for the solution but unable to find anything that says anything about this error.

Any help is highly appreciated.
