### ISSUE TITLE
Widget Title change...?

### ISSUE THREAD

**Issue by swathireddy2808** [capitalone/Hygieia#728]
How to chane the widget titles? want to replace with tool names.....
example: build is default widget name on dashboard want to change to Jenkins.

Could anyone help with this

**Comment by tabladrum** [comment]
You can change the title in the HTML such as this:
                <div class="row">
                    <div class="col-xs-12">
                        <widget name="feature" widget-title="Feature"></widget>
                        <widget name="repo"></widget>
                    </div>
                </div>

But I will say that this breaks the tools agnostic nature of Hygieia. You can use the build widget to show build from any build tool. From the other side, you could Jenkins to do more than builds. The whole idea is to capture the lifecycle events rather than a particular tool's output.

**Comment by swathireddy2808** [comment]
Great ! Thank you

**Comment by tabladrum** [comment]
Close it?

**Comment by satishc1** [comment]
Closed.

**Comment by poojithkumar** [comment]
@tabladrum  i want change widget name after the execution of config html. Is there any way to do that? name should depends on input.
 thank you
