### ISSUE TITLE
github-scm-collector Connection refused

### ISSUE THREAD

**Issue by gengweifeng** [capitalone/Hygieia#757]
Hi,
    i run the github-scm-collector in docker container using config as below
    

> #Database Name
database=dashboard
#Database HostName - default is localhost
dbhost=172.17.0.4
#Database Port - default is 27017
dbport=27017
#Database Username - default is blank
dbusername=db
#Database Password - default is blank
dbpassword=dbpass
#Collector schedule (required)
github.cron=0 0/5 * * * *
github.host=http://192.168.200.213:8000     
#Maximum number of days to go back in time when fetching commits
github.commitThresholdDays=15

then i use the **hygieia UI** create a team dashboard, and Code Repo info is

> 
![image](https://cloud.githubusercontent.com/assets/15317121/17761255/2229672c-6538-11e6-9614-6dc8cac70025.png)

but the github-scm-collector has error:

> 2016-08-18 14:30:00,102 ERROR c.c.d.collector.DefaultGitHubClient - I/O error on GET request for "http://192.168.200.213/api/v3/repos/8000/GengWeifeng/ku8manager-cluster/commits?sha=master&since=2016-08-18T14:20Z":Connect to 192.168.200.213:80 [/192.168.200.213] failed: Connection refused; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to 192.168.200.213:80 [/192.168.200.213] failed: Connection refused:http://192.168.200.213/api/v3/repos/8000/GengWeifeng/ku8manager-cluster/commits?sha=master&since=2016-08-18T14:20Z

why is is?

**Comment by gengweifeng** [comment]
the uri is my private gitlab, does it not support gitlab?

**Comment by mrpudn** [comment]
I'm not 100% sure on this, but I don't think the github collector supports gitlab - the gitlab API is likely not compatible with the github API. In order to add support for gitlab, you'd have to add a new collector.

**Comment by gengweifeng** [comment]
ok, thank you! I will try to add a new collector to support gitlab!
best wishes!

**Comment by dhakatev** [comment]
Hi, 

I am also facing same issue where after giving correct details and key getting below error

ERROR c.c.d.collector.DefaultGitHubClient - I/O error on GET request for "https://api.github.com/repos/mcdcorp/opentest/commits?sha=master&since=2018-02-22T15:10Z":Connect to api.github.com:443 [api.github.com/192.30.253.117, api.github.com/192.30.253.116] failed: Connection refused: connect; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to api.github.com:443 [api.github.com/192.30.253.117, api.github.com/192.30.253.116] failed: Connection refused: connect:https://api.github.com/repos/mcdcorp/opentest/commits?sha=master&since=2018-02-22T15:10Z

**Comment by gengweifeng** [comment]
I solved this issue by adding a new collector to support gitlab, because the interfaces are different between the github and gitlab.
