### ISSUE TITLE
Feature widget drop down - empty

### ISSUE THREAD

**Issue by bjayagop** [capitalone/Hygieia#818]
Hi,

The feature wideget drop down is just empty in the dashboard. 

Any suggestion to resolve?

Thanks
Jay

**Comment by MarkRx** [comment]
Check the troubleshooting guide @ https://github.com/capitalone/Hygieia/blob/master/collectors/feature/jira/README.md

It is probably the case that something isn't configured correctly in your settings.

**Comment by satishc1** [comment]
@bjayagop Closed. Reopen if still an issue.

The feature widget now has an option to display metrics based on the number of tickets instead of estimates. This is for setups that do not use estimates.
Functionality merged in https://github.com/capitalone/Hygieia/pull/1054 Use latest codebase. You’ll also need to follow cleanup instructions provided in https://github.com/capitalone/Hygieia/pull/1137
