### ISSUE TITLE
Bitbucket Collector (for Stash) Authentication is not working - Encryption bug

### ISSUE THREAD

**Issue by oshingc** [capitalone/Hygieia#902]
Hi Guys
I have the following error in the UI, please if something I'm missing I would like to know.

My properties file is:
```properties
debug=true
spring.jpa.show-sql: true
server.contextPath=/api
server.port=${PORT:0}

dbhost=localhost
dbport= 27017
dbname=dashboard
dbusername=dashboard
dbpassword=dashboard

git.cron=0 0/1 * * * *
git.host = http://stash.company.com/
git.api=/rest/api/1.0/
git.commitThresholdDays=15

git.credentials=(i put here my user:password encoded to 64 bits, is that right?)
git.key=(dont know what to put here)
git.product=server

logging.level.com.capitalone.dashboard=DEBUG
logging.level.com.capitalone.dashboard.collector=DEBUG
```

The error I'm getting:

![bitbucket error](https://cloud.githubusercontent.com/assets/3100819/19457556/6e40215e-948c-11e6-9275-f48a453de615.png)

Hope you can help me.

Thanks a lot! :D

**Comment by satishc1** [comment]
Functionality merged in https://github.com/capitalone/Hygieia/pull/835
Refer to the "Encryption for private repos" section in the UI module readme.

**Comment by oshingc** [comment]
Am I using wrong the properties file?

**Comment by satishc1** [comment]
Your props file above has this line..
git.key=(dont know what to put here)


1. From module core generate a secret key.
java -jar <path-to-jar>/core-2.0.2-SNAPSHOT.jar com.capitalone.dashboard.util.Encryption
2. Add this generated key to api.properties
### api.properties
key=<your-generated-key>
3. Add the same key to your repo settings file.
### git.properties
git.key=<your-generated-key>

**Comment by satishc1** [comment]
@oshingc 
First generate a key using this.
java -jar /core-2.0.2-SNAPSHOT.jar com.capitalone.dashboard.util.Encryption

Then add this key to the 2 properties files.

In api.properties the line should look like
key=yourgeneratedkey

In git.properties the line should look like
git.key=yourgeneratedkey

**Comment by oshingc** [comment]
I followed the steps, happily now the UI don't stuck at 'Error Encrypting Password', the userID and password are saved but I have errors at BitBucket Collector.

`2016-10-18 11:33:00,937 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from https://mybitbucket.company.com/rest/api/1.0/projects/projects/repos/PROJ/repos/myapplication/commits?until=master`

**Comment by MarkRx** [comment]
If you hit that URL with cURL or in your browser does it work?

https://mybitbucket.company.com/rest/api/1.0/projects/projects/repos/PROJ/repos/myapplication/commits?until=master

**Comment by oshingc** [comment]
No

**Comment by satishc1** [comment]
Does this link work ?
https://mybitbucket.company.com/rest/api/1.0/projects/PROJ/repos/myapplication/commits?until=master

apiPath + "/projects/" + projectKey + "/repos/" + repositorySlug + "/commits"

**Comment by oshingc** [comment]
Yes :O

**Comment by dinukool** [comment]
2016-10-19 16:11:54,015 ERROR c.c.d.c.DefaultBitbucketServerClient - Cannot decrypt this message
Given final block not properly padded
2016-10-19 16:11:54,111 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from https://stash.123.com/scm/myproj/devops.git/projects/mgtwy/repos/twy_com/commits?until=develop
org.springframework.web.client.HttpServerErrorException: 501 Not Implemented


Looking for your help -- @satishc1 @MarkRx Thanks!

**Comment by sivamadhankumar** [comment]
2016-10-20 23:55:00,066 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-10-20 23:55:00,069 INFO  c.c.d.collector.CollectorTask - Starting...
2016-10-20 23:55:00,070 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-10-20 23:55:00,671 INFO  c.c.d.collector.CollectorTask - Repo Count              0        0s
2016-10-20 23:55:00,672 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2016-10-20 23:55:00,672 INFO  c.c.d.collector.CollectorTask - Finished 

I am getting this as infinite loop when I tried to run this from my ubuntu14.0.4.

Here is my property file:


spring.data.mongodb.dbname=dashboarddb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=dashboarduser
spring.data.mongodb.password=dbpassword
git.cron=0 0/5 * * * *
git.host=https://bitbucket.com/projects/GP/repos/pcs-client/
git.api=/rest/api/1.0/
git.commitThresholdDays=15
git.pageSize=25
git.product=server

**Comment by satishc1** [comment]
@dinukool To setup password based authentication setup 
Refer to the "Encryption for private repos" section in the UI module readme.
@sivamadhankumar The log you have pasted shows INFO. The collector runs per the cron schedule that you setup in the properties file...ie it runs over and over and tries to collect.

**Comment by sivamadhankumar** [comment]
I am getting the following error when tried to run this command

 java -jar bitbucket-scm-collector-2.0.4-SNAPSHOT.jar --
spring.config.location=location of my property file.



 ERROR c.c.d.c.DefaultBitbucketServerClient - Cannot decrypt this message
Given final block not properly padded
2016-10-24 02:15:01,314 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from https:my repository url?until=master&limit=25
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]

**Comment by gowthamastute** [comment]
Assignees

No one assigned
Labels

None yet
Projects

None yet
Milestone

No milestone
Notifications

  Unsubscribe
You’re receiving notifications because you authored the thread.
1 participant

@gowthamastute
@gowthamastute
   
gowthamastute commented 29 minutes ago
Hi

When I run the Bitbucket collector it is automatically embedding "projects/repo" in middle of the URL, so I am getting 404 URL not found error.

My private Bitbucket URL is:
https://bitbucket.company.com/projects/PDC/repos/browse/.gitignore/commits?until=develop&limit=25

But the below URL is verified after executing collector to check for the commit so I am getting 404 not found error.

https://bitbucket.company.com/rest/api/1.0/projects/projects/repos/PDC/repos/browse/.gitignore/commits?until=develop&limit=25

URL embedded in between:
1./rest/api/1.0
2./projects/repo
The above stated is added in between my private URL. Please help me should I need to modify any file to rectify this error.

Property file:
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbusername=user
dbpassword=password
git.cron=0 0/5 * * * *
git.host=https://bitbucket.company.com
git.api=/rest/api/1.0/
git.username=username
git.password=password
git.key=hdqe40mYMhM9AemY9rgDiRfDIvepJb
github.key=hdqe40mYMhM9AemY9rgDiRfDIvepJb
git.commitThresholdDays=15
git.pageSize=25
git.product=server

I execute the below command
java -jar bitbucket-scm-collector-2.0.5-SNAPSHOT.jar --spring.config.location=/home/hygieiaconf/applicationbb.properties

Got output as:
2017-02-13 06:05:00,196 INFO c.c.d.collector.CollectorTask - Repo Count 2 0s
2017-02-13 06:05:00,196 INFO c.c.d.collector.CollectorTask - New Commits 0 0s
2017-02-13 06:05:00,196 INFO c.c.d.collector.CollectorTask - Finished 0s

Unable to get the commit count.

**Comment by preetcam** [comment]
@satishc1  : I am getting 404 error when I try to bit bitbucket url. Please guide how to construct the url .

My application.properties file
# mandatory:
git.host=stash.mycomapnyName.com
#git.api=/rest/api/1.0/   (I have tried uncommenting this line too, still same error)

In UI 

Repo URL -> https://stash.trusted.mycompanyName.com:7990/projects/CMR/repos/commsjavav2/browse

Error -> - Failed to obtain commits from https://stash.trusted.mycompanyName.com:7990/projects/projects/repos/CMR/repos/commsjavav2//commits?until=CHAO%2FCOMMS_17.1&limit=25

Not sure, why the code is appending /projects/repos/ to my URL. Please guide.

**Comment by navjottiwana** [comment]
Did anyone find a solution for the issue why the code is appending /projects/repos/ to the URL.
I am facing the same issue.
