### ISSUE TITLE
Jira Collector Not Showing Data

### ISSUE THREAD

**Issue by krismy93** [capitalone/Hygieia#95]
![screen shot 2015-08-26 at 1 16 30 pm](https://cloud.githubusercontent.com/assets/5998068/9505016/b8013f1c-4bf4-11e5-9a8f-2b03c952c880.png)

Jira collector not showing any data. Where would this error be occurring from? It can see all Scopes on Jira but Sprint Information not showing up

**Comment by amp5208** [comment]
@krismy93 , thank you for reaching out regarding your Jira question.  Based on our Gitter conversation, I believe that you are seeing "0"s on your dashboard because you are using a non-standard / custom Jira field to pull story point estimates.  Jira, by default, uses time based estimates using the <em>timeestimate</em> field, which is in business hours/days.  However, in an effort to make this dashboard more usable for different DevOps architectures, certain custom fields should be configurable via a property setting.

I believe that enabling field customization out of the box for Hygieia should be made a priority and should be added as an enhancement.  @tabladrum , Please mark this as an enhancement; I may have already created a similar issue on here; if that is the case, please close that issue and mark this as an enhancement.

**Comment by yqbjtu** [comment]
@krismy93,   Do you know how to config the communication from UI to API.  According to my understanding, the UI will get some data from  API, but it seems there is no any  setting property  for UI,  my API port is 8080, When I access http://xxxxx/api/dashboard,  I can see some dashboard json data, but When I config the build widget, there is no any build job to select. Jenkins collector is running well

**Comment by yqbjtu** [comment]
Thank you!

**Comment by tabladrum** [comment]
Can we close this?

**Comment by amp5208** [comment]
I believe that this issue should still be marked as a future enhancement for enabling field customization for Hygieia (see my comment above).  Otherwise, I would say this is closed, pending customer response.

**Comment by krismy93** [comment]
you can close this.
