### ISSUE TITLE
Unable to Build UI for Hygieia Dashboard

### ISSUE THREAD

**Issue by Mahendra1260** [capitalone/Hygieia#966]
I am unable to build UI component.
Below are the steps I have done so far.

Server is Linux

Step1: BuildHygieia package on server(server A)
Step2: Installed mongoDB on server A
Step3: Created the database and users as per the documentation
Step4: Build api package using dashboard.properties files
Step5: http://<serverA ip>:8086/api/dashboard giving me [] empty response (8086 is defined in my dashboard.properties file)
Step6: Trying to build UI component following documents. Document says installed on MAc or Install on Window. How about Installing on Linux? Also, is it manadatory to install using docker-compose or I can any other way?

**Comment by Mahendra1260** [comment]
Also if possible, can I have step by step installation documentation.

**Comment by mrpudn** [comment]
Docker is not required in order to run Hygieia.

For example, to install and start the API:
```bash
mvn install
java -jar api.jar --spring.config.location=dashboard.properties
```
I've been able to get Hygieia running on Linux following the same [Setup instructions](https://github.com/capitalone/Hygieia/blob/master/Setup.md).

If you encounter a specific error while trying to install and run the project on Linux, please feel free to open a new issue with logs and a description of your problem.

Thanks!
